CREATE TABLE cern_listing (
    department VARCHAR2(100),
    division VARCHAR2(100),
    Position VARCHAR2(100),
    worktag VARCHAR2(100),
    job_link CLOB,
    PRIMARY KEY (worktag)
);

CREATE TABLE cern_skills (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    worktag VARCHAR2(100),
    skills CLOB,
    PRIMARY KEY (id)
);

COMMIT;